### ISSUE TITLE
`max-width` only works with widths divisible by 40

### ISSUE THREAD

**Issue by tumusudheer** [emedvedev/attention-ocr#10]
Hi @emedvedev 

`aocr train datasets/training.tfrecords` command is throwing the following error:

```
2017-09-27 17:35:18.730416: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-27 17:35:18.730433: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-27 17:35:18.730437: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-27 17:35:18.730440: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-27 17:35:18.730443: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-09-27 17:35:18.924995: I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.8095
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.80GiB
2017-09-27 17:35:18.925019: I tensorflow/core/common_runtime/gpu/gpu_device.cc:927] DMA: 0 
2017-09-27 17:35:18.925023: I tensorflow/core/common_runtime/gpu/gpu_device.cc:937] 0:   Y 
2017-09-27 17:35:18.925032: I tensorflow/core/common_runtime/gpu/gpu_device.cc:996] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0
2017-09-27 17:35:18.957293: I tensorflow/core/common_runtime/direct_session.cc:265] Device mapping:
/job:localhost/replica:0/task:0/gpu:0 -> device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0

2017-09-27 17:35:18,957 root  INFO     loading data
2017-09-27 17:35:18,964 root  INFO     phase: train
2017-09-27 17:35:18,964 root  INFO     model_dir: checkpoints
2017-09-27 17:35:18,964 root  INFO     load_model: True
2017-09-27 17:35:18,964 root  INFO     output_dir: results
2017-09-27 17:35:18,964 root  INFO     steps_per_checkpoint: 100
2017-09-27 17:35:18,964 root  INFO     batch_size: 64
2017-09-27 17:35:18,964 root  INFO     num_epoch: 1000
2017-09-27 17:35:18,964 root  INFO     learning_rate: 1
2017-09-27 17:35:18,964 root  INFO     reg_val: 0
2017-09-27 17:35:18,964 root  INFO     max_gradient_norm: 5.000000
2017-09-27 17:35:18,964 root  INFO     clip_gradients: True
2017-09-27 17:35:18,964 root  INFO     max_image_width 300.000000
2017-09-27 17:35:18,964 root  INFO     max_prediction_length 30.000000
2017-09-27 17:35:18,964 root  INFO     target_vocab_size: 39
2017-09-27 17:35:18,964 root  INFO     target_embedding_size: 10.000000
2017-09-27 17:35:18,964 root  INFO     attn_num_hidden: 128
2017-09-27 17:35:18,964 root  INFO     attn_num_layers: 2
2017-09-27 17:35:18,965 root  INFO     visualize: True
Traceback (most recent call last):
  File "launcher.py", line 258, in <module>
    main()
  File "launcher.py", line 247, in main
    max_prediction_length=parameters.max_prediction,
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/models/model_2.0/models/emedvedev_attention-ocr/attention-ocr/aocr/model/model.py", line 165, in __init__
    use_gru=use_gru)
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/models/model_2.0/models/emedvedev_attention-ocr/attention-ocr/aocr/model/seq2seq_model.py", line 137, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/models/model_2.0/models/emedvedev_attention-ocr/attention-ocr/aocr/model/seq2seq.py", line 993, in model_with_buckets
    encoder_inputs = tf.split(encoder_inputs_tensor, bucket[0], 0)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1214, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3261, in _split
    num_split=num_split, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension size must be evenly divisible by 20 but is 21
        Number of ways to split should evenly divide the split dimension for 'model_with_buckets/split' (op: 'Split') with input shapes: [], [21,?,512] and with computed input tensors: input[0] = <0>.
```

Am I doing any thing wrong ?

Thanks in advance !!!

**Comment by emedvedev** [comment]
Make sure you are running the latest version, the dataset is created properly (did you use `aocr dataset` to do it?), and the image widths fit into the `max_image_width` limit.

**Comment by tumusudheer** [comment]
Hi @emedvedev ,

When I do max_image_width = 160 instead of 300, I'm not getting the error I mentioned earlier. Yeah I'm using aocr dataset to prepare the tfrecords and `aocr train` to train.

When I'm doing `aocr train`, I'm getting the following error:

```
Traceback (most recent call last):
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/bin/aocr", line 9, in <module>
    load_entry_point('aocr==0.2.1', 'console_scripts', 'aocr')()
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/__main__.py", line 238, in main
    model.train()
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/model/model.py", line 301, in train
    for batch in self.s_gen.gen(self.batch_size):
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/util/data_gen.py", line 59, in gen
    word = self.convert_lex(lex)
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/util/data_gen.py", line 78, in convert_lex
    assert lex and len(lex) < self.bucket_specs[-1][1]
AssertionError

```

```
Eg:  log
lex -----guttersnipe
len(lex)----11
('self.', '10')
```

I did `pip install aocr` to install my aocr module

**Comment by emedvedev** [comment]
You should also set `--max-prediction` to the maximum length of your predicted word/phrase. The default is 10, and you have words that are longer.

**Comment by tumusudheer** [comment]
Hi @emedvedev ,

Thank you very much for your response. I overlooked the MAX_PREDICTION flag in default, my mistake. I was able to start training though If I do not set the MAX_WIDTH to some number divisible by 40 or 80, I'm getting some weird error as follows, am I doing any thing wrong ?

One more questions is: do all my images have to be of the same size as MAX_WIDTH x MAX_HEIGHT (do I need to resize prior to prepare the data) , or is it good as long as all the images are within the limits of  MAX_WIDTH x MAX_HEIGHT ?

It would be great if you can provide a sample code how to test using a single image  or provide a sample snippet of how to create a standalone model by freezing graph and restoring checkpoint ?
I'm little confused on what kind of input placeholder I need to use to take input and how to initialize/ the model with the input placeholder to pass the input data to the model? 

Error with max_width = 600

```
Traceback (most recent call last):
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/bin/aocr", line 9, in <module>
    load_entry_point('aocr==0.2.1', 'console_scripts', 'aocr')()
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/__main__.py", line 235, in main
    max_prediction_length=parameters.max_prediction,
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/model/model.py", line 165, in __init__
    use_gru=use_gru)
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/model/seq2seq_model.py", line 137, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/model/seq2seq.py", line 988, in model_with_buckets
    encoder_inputs = tf.split(encoder_inputs_tensor, bucket[0], 0)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1214, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3261, in _split
    num_split=num_split, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension size must be evenly divisible by 80 but is 81
        Number of ways to split should evenly divide the split dimension for 'model_with_buckets/split' (op: 'Split') with input shapes: [], [81,?,512] and with computed input tensors: input[0] = <0>.
```

Error with MAx_WIDTH = 300

```
Traceback (most recent call last):
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/bin/aocr", line 9, in <module>
    load_entry_point('aocr==0.2.1', 'console_scripts', 'aocr')()
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/__main__.py", line 235, in main
    max_prediction_length=parameters.max_prediction,
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/model/model.py", line 165, in __init__
    use_gru=use_gru)
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/model/seq2seq_model.py", line 137, in __init__
    softmax_loss_function=softmax_loss_function)
  File "/home/sudheer/Flipkart/Research/maneesh/tensor_flow/local/lib/python2.7/site-packages/aocr/model/seq2seq.py", line 988, in model_with_buckets
    encoder_inputs = tf.split(encoder_inputs_tensor, bucket[0], 0)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1214, in split
    split_dim=axis, num_split=num_or_size_splits, value=value, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 3261, in _split
    num_split=num_split, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2508, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1873, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1823, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimension size must be evenly divisible by 40 but is 41
        Number of ways to split should evenly divide the split dimension for 'model_with_buckets/split' (op: 'Split') with input shapes: [], [41,?,512] and with computed input tensors: input[0] = <0>.
```

But if I used 320 or 640 for Max_width, I'm not getting any of the above errors

Thank you.

**Comment by emedvedev** [comment]
Oh. I will have to fix the faulty `max-width` values, but yes, for now it should be fine to find the nearest one that works.

> One more questions is: do all my images have to be of the same size as MAX_WIDTH x MAX_HEIGHT (do I need to resize prior to prepare the data) , or is it good as long as all the images are within the limits of MAX_WIDTH x MAX_HEIGHT ?

It's good as long as the images are within the limits. They will just be padded if necessary.

> I'm little confused on what kind of input placeholder I need to use to take input and how to initialize/ the model with the input placeholder to pass the input data to the model?

There is a single input placeholder, `input_image_as_bytes`, and [a single output](https://github.com/emedvedev/attention-ocr/blob/master/aocr/model/model.py#L202). `input_image_as_bytes` will accept either a single image or an array of images, and the output will give either a string or an array of strings, respectively.

**Comment by ckirmse** [comment]
I think it's more complicated than just widths divisible by 40--max_width of 320 and max_height of 48 works, but --max_width of 320 and max_height of 32 does not work. I've been trying to figure out exactly what's going on but I haven't solved it yet. Any thoughts?

**Comment by TannerGilbert** [comment]
Still having problems with this. Can you share an example on how to match width, height and prediction_length as do not get a error
