### ISSUE TITLE
NotImplementedError on training

### ISSUE THREAD

**Issue by mattfeury** [emedvedev/attention-ocr#11]
Hi! First off thanks for this repo. It's been immensely helpful. I've hit a few snags but I've been able to work around them (can submit a PR if wanted). But on occasion during training I see this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/aocr", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/aocr/__main__.py", line 238, in main
    model.train()
  File "/usr/local/lib/python2.7/site-packages/aocr/model/model.py", line 301, in train
    for batch in self.s_gen.gen(self.batch_size):
  File "/usr/local/lib/python2.7/site-packages/aocr/util/data_gen.py", line 65, in gen
    go_shift=1)
  File "/usr/local/lib/python2.7/site-packages/aocr/util/bucketdata.py", line 42, in flush_out
    raise NotImplementedError
```

I'm able to dig into the code and see where this is obviously raised for probably a good reason, but am not sure what the core reason is. Any thoughts as to why this might be happening? i'm assuming something with my dataset?

thanks!

**Comment by emedvedev** [comment]
What about `max-prediction-length`? This error will be raised when the decoder size (i.e. the maximum size of the predicted output) is more than the `max-prediction-length` value. The default is `8`, so it wouldn't be enough if your dataset has, for example, long words.

**Comment by emedvedev** [comment]
And of course PRs are welcome!

**Comment by mattfeury** [comment]
think this was a max prediction length issue. had some bad data in there that i did not expect.
