### ISSUE TITLE
AssertionError while training

### ISSUE THREAD

**Issue by aggrowal** [emedvedev/attention-ocr#158]
While training the model following error occurs:

`
Colocation members, user-requested devices, and framework assigned devices, if any:
  MutableHashTable (MutableHashTableV2) /device:GPU:0
  MutableHashTable_lookup_table_export_values/LookupTableExportV2 (LookupTableExportV2) /device:GPU:0
  MutableHashTable_lookup_table_insert/LookupTableInsertV2 (LookupTableInsertV2) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Enter (Enter) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Enter_1 (Enter) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Switch (Switch) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Enter_2 (Enter) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Enter_3 (Enter) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2/Switch_2 (Switch) /device:GPU:0
  map_1/while/foldr/while/cond/MutableHashTable_lookup_table_find/LookupTableFindV2 (LookupTableFindV2) /device:GPU:0

Traceback (most recent call last):
  File "C:\Users\Rohan Aggarwal\AppData\Local\Programs\Python\Python37\Scripts\aocr-script.py", line 11, in <module>
    load_entry_point('aocr==0.7.6', 'console_scripts', 'aocr')()
  File "c:\users\rohan aggarwal\appdata\local\programs\python\python37\lib\site-packages\aocr\__main__.py", line 257, in main      
    num_epoch=parameters.num_epoch
  File "c:\users\rohan aggarwal\appdata\local\programs\python\python37\lib\site-packages\aocr\model\model.py", line 376, in train  
    for batch in s_gen.gen(self.batch_size):
  File "c:\users\rohan aggarwal\appdata\local\programs\python\python37\lib\site-packages\aocr\util\data_gen.py", line 71, in gen   
    word = self.convert_lex(lex)
  File "c:\users\rohan aggarwal\appdata\local\programs\python\python37\lib\site-packages\aocr\util\data_gen.py", line 89, in convert_lex
    assert len(lex) < self.bucket_specs[-1][1]
AssertionError
`

I know this is due to data_gen.py file but I am unable to work around it, anyone knows the solution ?

**Comment by adwaitbhope** [comment]
Can you let me know your solution to this error?

**Comment by Daornit** [comment]
why you closed it without any explanation ?
