### ISSUE TITLE
show AssertionError when I run "aocr train training.tfrecords"

### ISSUE THREAD

**Issue by tea321000** [emedvedev/attention-ocr#2]
I have a sample.txt with the text such as "./1391/4/361_Kindest_42517.jpg kindest"and corresponding jpg in that directory, and I succeed in build training.tfrecords.But when I run "aocr train training.tfrecords",it shows error below:
Traceback (most recent call last):
  File "/usr/local/bin/aocr", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/aocr/__main__.py", line 199, in main
    model.train()
  File "/usr/local/lib/python2.7/dist-packages/aocr/model/model.py", line 298, in train
    for batch in self.s_gen.gen(self.batch_size):
  File "/usr/local/lib/python2.7/dist-packages/aocr/util/data_gen.py", line 68, in gen
    word = self.convert_lex(lex)
  File "/usr/local/lib/python2.7/dist-packages/aocr/util/data_gen.py", line 94, in convert_lex
    assert lex and len(lex) < self.bucket_specs[-1][1]
AssertionError
how can I deal with this problem?

**Comment by emedvedev** [comment]
In the [model.py](https://github.com/emedvedev/attention-ocr/blob/master/aocr/model/model.py#L47), change `max_image_width` and `max_prediction_length`. 

On a related note, both arguments should really be exposed as CLI parameters, and I would welcome a PR on it if you have the time.

**Comment by gabrielziegler3** [comment]
I'm sorry @emedvedev , how exactly should these parameters be adjusted?

**Comment by emedvedev** [comment]
Prediction length can be adjusted with the `--max-prediction` CLI parameter now.

**Comment by gabrielziegler3** [comment]
Indeed that solved! Problem was that I kept changing the `max_prediction_length` in model.py and it was always overwritten by the cli default arguments.
Thanks

**Comment by mohammad228** [comment]
how much must be set  this parameter?

**Comment by mohammad228** [comment]
I have this error when i train:
2020-12-05 14:03:20,638 root  INFO     Step 1: 6.937s, loss: 3.699641, perplexity: 40.432805.
Traceback (most recent call last):
  File "/home/girizliii/.local/bin/aocr", line 8, in <module>
    sys.exit(main())
  File "/home/girizliii/.local/lib/python2.7/site-packages/aocr/__main__.py", line 257, in main
    num_epoch=parameters.num_epoch
  File "/home/girizliii/.local/lib/python2.7/site-packages/aocr/model/model.py", line 376, in train
    for batch in s_gen.gen(self.batch_size):
  File "/home/girizliii/.local/lib/python2.7/site-packages/aocr/util/data_gen.py", line 70, in gen
    if self.max_width and (Image.open(IO(img)).size[0] <= self.max_width):
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
IOError: cannot identify image file <StringIO.StringIO instance at 0x7f834c23ef00>
