### ISSUE TITLE
TypeError: descriptor 'encode' requires a 'unicode' object but received a 'str'

### ISSUE THREAD

**Issue by rishikelltontech** [emedvedev/attention-ocr#20]
Hi,

I am getting the "TypeError: descriptor 'encode' requires a 'unicode' object but received a 'str'" when I build a TFRecords dataset by ruuing "aocr dataset ./datasets/annotations-training.txt ./datasets/training.tfrecords" command.

**Following is the error traceback:**

2017-10-09 23:49:00.678817: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-09 23:49:00.678867: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-09 23:49:00.678880: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-09 23:49:00,680 root  INFO     Building a dataset from ./datasets/annotations-training.txt.
2017-10-09 23:49:00,680 root  INFO     Output file: ./datasets/training.tfrecords
Traceback (most recent call last):
  File "/usr/local/bin/aocr", line 11, in <module>
    load_entry_point('aocr==0.3.0', 'console_scripts', 'aocr')()
  File "/usr/local/lib/python2.7/dist-packages/aocr/__main__.py", line 209, in main
    dataset.generate(parameters.annotations_path, parameters.output_path, parameters.log_step)
  File "/usr/local/lib/python2.7/dist-packages/aocr/util/dataset.py", line 29, in generate
    'label': _bytes_feature(text_type.encode(label))}))
TypeError: descriptor 'encode' requires a 'unicode' object but received a 'str'

**Comment by emedvedev** [comment]
Please checkout `master` and try again: I've just merged https://github.com/emedvedev/attention-ocr/pull/17 that should fix the issue.

**Comment by rishikelltontech** [comment]
Thanks. It working
