### ISSUE TITLE
error running aocr

### ISSUE THREAD

**Issue by yanpozka** [emedvedev/attention-ocr#48]
After installing **aocr** (`pip install aocr`) in both my OS and the official tensor docker container(**gcr.io/tensorflow/tensorflow**) I'm getting this error even when I run `aocr --help`:
```bash
Traceback (most recent call last):
  File "/usr/local/bin/aocr", line 7, in <module>
    from aocr.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/aocr/__main__.py", line 15, in <module>
    from .model.model import Model
  File "/usr/local/lib/python2.7/dist-packages/aocr/model/model.py", line 20, in <module>
    from .seq2seq_model import Seq2SeqModel
  File "/usr/local/lib/python2.7/dist-packages/aocr/model/seq2seq_model.py", line 27, in <module>
    from .seq2seq import model_with_buckets
  File "/usr/local/lib/python2.7/dist-packages/aocr/model/seq2seq.py", line 74, in <module>
    linear = rnn_cell._linear  # pylint: disable=protected-access
AttributeError: 'module' object has no attribute '_linear'
```

```bash
# uname -a
Linux 71e18aa0cfc4 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by AdamWP** [comment]
In some versions of TF _linear was moved from rnn_cell to rnn_cell_impl.

You need to modify /usr/local/lib/python2.7/dist-packages/aocr/model/seq2seq.py

Change line 71 from "from tensorflow.contrib.rnn.python.ops import rnn, rnn_cell"
to 
"from tensorflow.contrib.rnn.python.ops import rnn
from tensorflow.python.ops import rnn_cell_impl"

Change line 74 "linear = rnn_cell._linear" to "rnn_cell_impl._linear"

**Comment by emedvedev** [comment]
Yup, looks like it's been moved in 1.4, so aocr is lagging a little behind. 

@AdamWP would you mind submitting a PR? Ideally with a conditional `import`, to keep compatibility with the older TF versions.

**Comment by AdamWP** [comment]
@emedvedev Done!

**Comment by emedvedev** [comment]
Thanks! Closing the issue.

**Comment by avielas** [comment]
but how did you solved that?

**Comment by avielas** [comment]
@emedvedev but how did you solved that?

**Comment by emedvedev** [comment]
@avielas https://github.com/emedvedev/attention-ocr/pull/51

**Comment by avielas** [comment]
thanks so much!!

**Comment by avielas** [comment]
@emedvedev #51 didn't work for me. I used tensorflow version 1.4.0 on ubuntu 16. my seq2seq.py:

from tensorflow.python.ops import nn_ops
from tensorflow.contrib.rnn.python.ops import rnn
from tensorflow.python.ops import variable_scope

try:
    from tensorflow.contrib.rnn.python.ops import rnn_cell_impl
except ImportError:
    from tensorflow.python.ops import rnn_cell_impl

try:
    linear = rnn_cell_impl._linear  # pylint: disable=protected-access
except AttributeError:
    from tensorflow.contrib.rnn.python.ops import core_rnn_cell
    linear = core_rnn_cell._linear  # pylint: disable=protected-access

Any ideas?

**Comment by emedvedev** [comment]
Can you paste the full error log you’re getting? Maybe there’s been another change between TF versions.

**Comment by avielas** [comment]
**sure:**
(virtualenv_attention) <user>@<computer-name>:~/DL/attention-ocr$ sudo aocr dataset ./datasets/annotations-training.txt ./datasets/training.tfrecords
Traceback (most recent call last):
  File "/usr/local/bin/aocr", line 7, in <module>
    from aocr.__main__ import main
  File "/usr/local/lib/python2.7/dist-packages/aocr/__main__.py", line 15, in <module>
    from .model.model import Model
  File "/usr/local/lib/python2.7/dist-packages/aocr/model/model.py", line 20, in <module>
    from .seq2seq_model import Seq2SeqModel
  File "/usr/local/lib/python2.7/dist-packages/aocr/model/seq2seq_model.py", line 27, in <module>
    from .seq2seq import model_with_buckets
  File "/usr/local/lib/python2.7/dist-packages/aocr/model/seq2seq.py", line 83, in <module>
    linear = core_rnn_cell._linear  # pylint: disable=protected-access
AttributeError: 'module' object has no attribute '_linear'

**Comment by avielas** [comment]
I tried tf 1.2 1.4 1.8. what exactly version should I use?

**Comment by avielas** [comment]
update error(tf 1.2):
(virtualenv_aocr_0_7_3) <user>@computer-name:~/DL/aocr-0.7.3$ sudo aocr dataset ./datasets/annotations-training.txt ./datasets/training.tfrecords
Traceback (most recent call last):
  File "/usr/local/bin/aocr", line 9, in <module>
    load_entry_point('aocr==0.7.3', 'console_scripts', 'aocr')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/aocr/__main__.py", line 15, in <module>
  File "build/bdist.linux-x86_64/egg/aocr/model/model.py", line 20, in <module>
  File "build/bdist.linux-x86_64/egg/aocr/model/seq2seq_model.py", line 27, in <module>
  File "build/bdist.linux-x86_64/egg/aocr/model/seq2seq.py", line 83, in <module>
AttributeError: 'module' object has no attribute '_linear'

**Comment by emedvedev** [comment]
Thanks! One more thing: which aocr version are you running, and is there a difference in the error logs between the latest version in pip and the github master?
