### ISSUE TITLE
Unable to export model

### ISSUE THREAD

**Issue by subhadeepdas91** [emedvedev/attention-ocr#6]
While exporting the model by using command
aocr export exported-model
following error is shown

subhadeep@sd-vm:~/Desktop/tensorflow_ocr/new_ocr$ aocr export exported-model
2017-08-31 18:06:08.565366: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-08-31 18:06:08.565580: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
Traceback (most recent call last):
  File "/home/subhadeep/.local/bin/aocr", line 11, in <module>
    sys.exit(main())
  File "/home/subhadeep/.local/lib/python2.7/site-packages/aocr/__main__.py", line 215, in main
    data_path=parameters.dataset_path,
AttributeError: 'Namespace' object has no attribute 'dataset_path'

**Comment by emedvedev** [comment]
Hi! Export is, unfortunately, not completely implemented yet, but I'll try to do it sometime next week.

**Comment by tumusudheer** [comment]
Hi @emedvedev ,

 It would be great if you can please provide export and freezing graph code if you have already implemented.

Thanks in advance!!!

**Comment by mattfeury** [comment]
would love to see this done as well. training the model is great, but now i'd like to do some cool stuff with it! any way i could help?

**Comment by emedvedev** [comment]
Just letting you guys know that I've implemented the model export. There are two possible formats: a [frozen graph](https://blog.metaflow.fr/tensorflow-how-to-freeze-a-model-and-serve-it-with-a-python-api-d4f3596b3adc) or a SavedModel ready for [TensorFlow Serving](https://www.tensorflow.org/serving/).

Finally closing the issue :)

**Comment by tumusudheer** [comment]
Thank you very much @emedvedev
