### ISSUE TITLE
Problem while training with datasets.tfrecords

### ISSUE THREAD

**Issue by vedarddy** [emedvedev/attention-ocr#61]
Traceback (most recent call last):
  File "/home/phani/Documents/AOCR/attention-ocr/aocr/__main__.py", line 277, in <module>
    main()
  File "/home/phani/Documents/AOCR/attention-ocr/aocr/__main__.py", line 252, in main
    num_epoch=parameters.num_epoch            )
  File "/home/phani/Documents/AOCR/attention-ocr/aocr/model/model.py", line 348, in train
    for batch in s_gen.gen(self.batch_size):
  File "/home/phani/Documents/AOCR/attention-ocr/aocr/util/data_gen.py", line 71, in gen
    word = self.convert_lex(lex)
  File "/home/phani/Documents/AOCR/attention-ocr/aocr/util/data_gen.py", line 97, in convert_lex
    assert len(lex) <= self.bucket_specs[-1][1]
AssertionError

self.bucket_specs[-1][1] gives me a value of 10 always because bucket_specs = [(22,10)]
len(lex) is the length of the label the longest of which is 19 characters so the assertion fails

What does the parameter bucket_specs refer to and how do I fix this error?

**Comment by emedvedev** [comment]
The `max-prediction` parameter is set to 8 by default, so it'll error out on labels longer than 8 characters. Just set it to whatever makes sense for you in the CLI when you run the training subcommand.
