### ISSUE TITLE
No such process

### ISSUE THREAD

**Issue by nickppbd** [emedvedev/attention-ocr#64]
this error happened at tensorflow 1.5 in Window 10
./datasets/annotations-training.txt file shold be in there? 
I can't find annotations-training.txt anywhere.

C:\Users\kimduknam>aocr dataset ./datasets/annotations-training.txt ./datasets/training.tfrecords
2018-02-05 13:14:41.835884: I C:\tf_jenkins\workspace\rel-win\M\windows\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX AVX2
2018-02-05 13:14:41,826 root  INFO     Building a dataset from ./datasets/annotations-training.txt.
2018-02-05 13:14:41,826 root  INFO     Output file: ./datasets/training.tfrecords
Traceback (most recent call last):
  File "c:\users\kimduknam\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\kimduknam\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\kimduknam\AppData\Local\Programs\Python\Python36\Scripts\aocr.exe\__main__.py", line 9, in <module>
  File "c:\users\kimduknam\appdata\local\programs\python\python36\lib\site-packages\aocr\__main__.py", line 219, in main
    dataset.generate(parameters.annotations_path, parameters.output_path, parameters.log_step, parameters.force_uppercase, parameters.save_filename)
  File "c:\users\kimduknam\appdata\local\programs\python\python36\lib\site-packages\aocr\util\dataset.py", line 19, in generate
    writer = tf.python_io.TFRecordWriter(output_path)
  File "c:\users\kimduknam\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\lib\io\tf_record.py", line 106, in __init__
    compat.as_bytes(path), compat.as_bytes(compression_type), status)
  File "c:\users\kimduknam\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Failed to create a NewWriteableFile: ./datasets/training.tfrecords : \udcc1\udcf6\udcc1\udca4\udcb5\udcc8 \udcb0\udce6\udcb7θ\udca6 ã\udcc0\udcbb \udcbc\udcf6 \udcbe\udcf8\udcbd\udcc0\udcb4ϴ\udcd9.
; No such process

**Comment by emedvedev** [comment]
Hi,

You need your own set of images with labels as well as your own annotations file. See _[create 
a dataset](https://github.com/emedvedev/attention-ocr#create-a-dataset)_ in the README.

**Comment by nickppbd** [comment]
@emedvedev I got it. Thank you:)
