### ISSUE TITLE
OSError in visualizing results

### ISSUE THREAD

**Issue by masonsun** [emedvedev/attention-ocr#73]
When I run `aocr test --visualize test.tfrecords`, it throws the error `OSError: cannot write mode RGBA as JPEG`.

I have tried converting all my test images to JPGs and removing the alpha channels, but this doesn't seem to work. Any tips?

**Comment by masonsun** [comment]
Thanks for the quick response. Here it is:

`(tensorflow_p36) ubuntu@ip-10-0-0-201:~/aocr_module/data$ aocr test --visualize test.tfrecords
2018-03-23 17:26:50.385278: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-03-23 17:26:50.470643: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:895] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-23 17:26:50.470975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1105] Found device 0 with properties:
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-03-23 17:26:50.471005: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
2018-03-23 17:26:50,822 root  INFO     phase: test
2018-03-23 17:26:50,822 root  INFO     model_dir: ./checkpoints
2018-03-23 17:26:50,823 root  INFO     load_model: True
2018-03-23 17:26:50,823 root  INFO     output_dir: ./results
2018-03-23 17:26:50,823 root  INFO     steps_per_checkpoint: 0
2018-03-23 17:26:50,823 root  INFO     batch_size: 1
2018-03-23 17:26:50,823 root  INFO     learning_rate: 1
2018-03-23 17:26:50,823 root  INFO     reg_val: 0
2018-03-23 17:26:50,823 root  INFO     max_gradient_norm: 5.000000
2018-03-23 17:26:50,823 root  INFO     clip_gradients: True
2018-03-23 17:26:50,823 root  INFO     max_image_width 160.000000
2018-03-23 17:26:50,823 root  INFO     max_prediction_length 8.000000
2018-03-23 17:26:50,823 root  INFO     channels: 1
2018-03-23 17:26:50,823 root  INFO     target_embedding_size: 10.000000
2018-03-23 17:26:50,823 root  INFO     attn_num_hidden: 128
2018-03-23 17:26:50,824 root  INFO     attn_num_layers: 2
2018-03-23 17:26:50,824 root  INFO     visualize: True
2018-03-23 17:26:52,635 root  INFO     Reading model parameters from ./checkpoints/model.ckpt-615
2018-03-23 17:26:52.847312: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1195] Creating TensorFlow device (/device:GPU:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
2018-03-23 17:26:54,115 root  INFO     Step 1 (0.996s). Accuracy: 100.00%, loss: 0.008003, perplexity: 1.00803, probability: 94.50% 100% (936MTB)
2018-03-23 17:26:54,171 root  INFO     Step 2 (0.030s). Accuracy: 100.00%, loss: 0.005997, perplexity: 1.00602, probability: 95.80% 100% (CN1309)
2018-03-23 17:26:54,232 root  INFO     Step 3 (0.028s). Accuracy: 100.00%, loss: 0.008799, perplexity: 1.00884, probability: 94.49% 100% (ILEG0)
2018-03-23 17:26:54,269 root  INFO     Step 4 (0.029s). Accuracy: 100.00%, loss: 0.005638, perplexity: 1.00565, probability: 96.08% 100% (APC838)
2018-03-23 17:26:54,312 root  INFO     Step 5 (0.031s). Accuracy: 100.00%, loss: 0.007495, perplexity: 1.00752, probability: 94.12% 100% (KYP4595)
2018-03-23 17:26:54,348 root  INFO     Step 6 (0.029s). Accuracy: 100.00%, loss: 0.013060, perplexity: 1.01315, probability: 90.06% 100% (SAMPLE1)
2018-03-23 17:26:54,396 root  INFO     Step 7 (0.028s). Accuracy: 100.00%, loss: 0.006822, perplexity: 1.00685, probability: 95.26% 100% (DWH486)
2018-03-23 17:26:54,433 root  INFO     Step 8 (0.028s). Accuracy: 100.00%, loss: 0.005345, perplexity: 1.00536, probability: 96.31% 100% (ABC123)
2018-03-23 17:26:54,483 root  INFO     Step 9 (0.029s). Accuracy: 100.00%, loss: 0.016637, perplexity: 1.01678, probability: 88.73% 100% (683ZCL)
2018-03-23 17:26:54,523 root  INFO     Step 10 (0.029s). Accuracy: 100.00%, loss: 0.011873, perplexity: 1.01194, probability: 90.92% 100% (JSD7911)
2018-03-23 17:26:54,571 root  INFO     Step 11 (0.029s). Accuracy: 100.00%, loss: 0.003247, perplexity: 1.00325, probability: 97.68% 100% (SKT517)
2018-03-23 17:26:54,610 root  INFO     Step 12 (0.029s). Accuracy: 100.00%, loss: 0.002507, perplexity: 1.00251, probability: 98.24% 100% (PS2411)
2018-03-23 17:26:54,665 root  INFO     Step 13 (0.029s). Accuracy: 100.00%, loss: 0.012405, perplexity: 1.01248, probability: 91.61% 100% (M0T0RZ)
2018-03-23 17:26:54,716 root  INFO     Step 14 (0.029s). Accuracy: 100.00%, loss: 0.007065, perplexity: 1.00709, probability: 95.09% 100% (P0PQIZ)
2018-03-23 17:26:54,759 root  INFO     Step 15 (0.029s). Accuracy: 100.00%, loss: 0.004199, perplexity: 1.00421, probability: 97.40% 100% (874J)
2018-03-23 17:26:54,798 root  INFO     Step 16 (0.030s). Accuracy: 100.00%, loss: 0.008821, perplexity: 1.00886, probability: 93.16% 100% (AGB7548)
2018-03-23 17:26:54,889 root  INFO     Step 17 (0.030s). Accuracy: 100.00%, loss: 0.008697, perplexity: 1.00873, probability: 94.07% 100% (WM2048)
2018-03-23 17:26:54,930 root  INFO     Step 18 (0.028s). Accuracy: 100.00%, loss: 0.002271, perplexity: 1.00227, probability: 98.17% 100% (4141119)
2018-03-23 17:26:54,975 root  INFO     Step 19 (0.029s). Accuracy: 100.00%, loss: 0.045520, perplexity: 1.04657, probability: 72.66% 100% (1416EH)
2018-03-23 17:26:55,015 root  INFO     Step 20 (0.029s). Accuracy: 100.00%, loss: 0.008028, perplexity: 1.00806, probability: 94.52% 100% (OAM145)
2018-03-23 17:26:55,074 root  INFO     Step 21 (0.029s). Accuracy: 100.00%, loss: 0.041483, perplexity: 1.04236, probability: 74.74% 100% (800002)
2018-03-23 17:26:55,129 root  INFO     Step 22 (0.029s). Accuracy: 100.00%, loss: 0.003008, perplexity: 1.00301, probability: 97.87% 100% (CD8065)
2018-03-23 17:26:55,165 root  INFO     Step 23 (0.029s). Accuracy: 100.00%, loss: 0.062408, perplexity: 1.06440, probability: 64.57% 100% (194MJM)
2018-03-23 17:26:55,218 root  INFO     Step 24 (0.030s). Accuracy: 100.00%, loss: 0.035074, perplexity: 1.03570, probability: 75.43% 100% (5NNY092)
2018-03-23 17:26:55,256 root  INFO     Step 25 (0.029s). Accuracy: 100.00%, loss: 0.002727, perplexity: 1.00273, probability: 98.07% 100% (800002)
2018-03-23 17:26:55,297 root  INFO     Step 26 (0.029s). Accuracy: 100.00%, loss: 0.007600, perplexity: 1.00763, probability: 94.05% 100% (M0000SE)
2018-03-23 17:26:55,357 root  INFO     Step 27 (0.030s). Accuracy: 100.00%, loss: 0.008760, perplexity: 1.00880, probability: 93.19% 100% (ABD1840)
2018-03-23 17:26:55,397 root  INFO     Step 28 (0.028s). Accuracy: 100.00%, loss: 0.002449, perplexity: 1.00245, probability: 97.81% 100% (8812044)
2018-03-23 17:26:55,435 root  INFO     Step 29 (0.029s). Accuracy: 100.00%, loss: 0.008625, perplexity: 1.00866, probability: 94.13% 100% (002AGN)
2018-03-23 17:26:55,470 root  INFO     Step 30 (0.029s). Accuracy: 100.00%, loss: 0.004351, perplexity: 1.00436, probability: 97.41% 100% (URSAE)
2018-03-23 17:26:55,515 root  INFO     Step 31 (0.029s). Accuracy: 100.00%, loss: 0.008524, perplexity: 1.00856, probability: 92.56% 100% (H694856)
2018-03-23 17:26:55,552 root  INFO     Step 32 (0.029s). Accuracy: 100.00%, loss: 0.003799, perplexity: 1.00381, probability: 98.22% 100% (692)
2018-03-23 17:26:55,599 root  INFO     Step 33 (0.030s). Accuracy: 100.00%, loss: 0.014248, perplexity: 1.01435, probability: 90.43% 100% (627WWI)
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 605, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/bin/aocr", line 11, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/aocr/__main__.py", line 256, in main
    data_path=parameters.dataset_path
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/aocr/model/model.py", line 323, in test
    self.visualize_attention(batch['data'], step_attns[0], output, ground, incorrect)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/aocr/model/model.py", line 487, in visualize_attention
    img_out.save(output_filename)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/PIL/Image.py", line 1930, in save
    save_handler(self, fp, filename)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 607, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG`

**Comment by emedvedev** [comment]
Thanks!

It would be great if you could help with testing a little: can you replace `img_out.save(output_filename)` with `img_out.convert("RGB").save(output_filename)` in `model/model.py` and verify that it works?

**Comment by emedvedev** [comment]
As an aside, you're running an outdated version of the module, and the latest one shouldn't have this error. Is there something that's preventing you from updating?

**Comment by masonsun** [comment]
Thanks for all the help. It seems that running `pip install aocr` as is actually installs v0.7.0, which does not contain the updated `visualize_attention` function. After your newest commit and upgrading the `aocr` module via pip, everything works fine!

Closing the issue (:
