### ISSUE TITLE
Invalid PNG data, size ###

### ISSUE THREAD

**Issue by alpexjava** [emedvedev/attention-ocr#91]
Environment:
Ubuntu 16, 
GPU:  GTX 1060/6Mb
Tensorflow: v1.5
CuDNN 7.*
Cuda 9.1

1.  Datasets i've created and tried to train contain 120 000(small) - 15 000 000 (big) images(png)/labels. 
2. tfrecords created succesfully
3. training comes up with the same error after a few hundred/thousand steps:
aocr train ./tfrecords/train.tfrecords steps-per-checkpoints=500 batch-size=512 --num-epoch=5 --max-predictions=18 --max-height=32 --max-width=159
. . . . . . .
2018-05-23 20:33:17,104 root  INFO     Step 158: 0.776s, loss: 1.708350, perplexity: 5.519846.
2018-05-23 20:33:18,003 root  INFO     Step 159: 0.776s, loss: 1.719668, perplexity: 5.582677.
2018-05-23 20:33:18,899 root  INFO     Step 160: 0.780s, loss: 1.714975, perplexity: 5.556535.
2018-05-23 20:33:19,830 root  INFO     Step 161: 0.808s, loss: 1.615288, perplexity: 5.029339.
2018-05-23 20:33:20,736 root  INFO     Step 162: 0.776s, loss: 1.676965, perplexity: 5.349294.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
**tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid PNG data, size 837**
	 [[Node: map/while/DecodePng = DecodePng[channels=1, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayReadV3)]]
	 [[Node: map/while/truediv_1/x/_64 = _HostSend[T=DT_INT32, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_870_map/while/truediv_1/x", _device="/job:localhost/replica:0/task:0/device:GPU:0"](map/while/truediv_1/x)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/aocr", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/aocr/__main__.py", line 252, in main
    num_epoch=parameters.num_epoch
  File "/usr/local/lib/python3.5/dist-packages/aocr/model/model.py", line 380, in train
    result = self.step(batch, self.forward_only)
  File "/usr/local/lib/python3.5/dist-packages/aocr/model/model.py", line 461, in step
    outputs = self.sess.run(output_feed, input_feed)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)

**tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid PNG data, size 837**

	 [[Node: map/while/DecodePng = DecodePng[channels=1, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayReadV3)]]
	 [[Node: map/while/truediv_1/x/_64 = _HostSend[T=DT_INT32, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_870_map/while/truediv_1/x", _device="/job:localhost/replica:0/task:0/device:GPU:0"](map/while/truediv_1/x)]]

Caused by op 'map/while/DecodePng', defined at:
  File "/usr/local/bin/aocr", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/aocr/__main__.py", line 246, in main
    channels=parameters.channels,
  File "/usr/local/lib/python3.5/dist-packages/aocr/model/model.py", line 122, in __init__
    self.img_data = tf.map_fn(self._prepare_image, self.img_data, dtype=tf.float32)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/functional_ops.py", line 409, in map_fn
    swap_memory=swap_memory)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2934, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2720, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2662, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/functional_ops.py", line 399, in compute
    packed_fn_values = fn(packed_values)
  File "/usr/local/lib/python3.5/dist-packages/aocr/model/model.py", line 481, in _prepare_image
    img = tf.image.decode_png(image, channels=self.channels)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_image_ops.py", line 709, in decode_png
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

**InvalidArgumentError (see above for traceback): Invalid PNG data, size 837**

	 [[Node: map/while/DecodePng = DecodePng[channels=1, dtype=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:CPU:0"](map/while/TensorArrayReadV3)]]
	 [[Node: map/while/truediv_1/x/_64 = _HostSend[T=DT_INT32, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_870_map/while/truediv_1/x", _device="/job:localhost/replica:0/task:0/device:GPU:0"](map/while/truediv_1/x)]]
=====================================================
I couldn't understand the error and source of the error.
=====================================================
I tried short words in dataset, max 8 = it was working and i could get longest training.
As far as you didn't provide limitation for longest word (just instruction max-predictions=10 (or longer, say 18) looks like  not enough and training crashes)
What do you think, please? or What did i miss or did wrong?

Regards,
Alexei P.
 
p.s.
Sorry for wrongly formatted text in the post

**Comment by emedvedev** [comment]
Looks like some of the images in your dataset are corrupted, or at least TensorFlow can't read them. I don't think it has anything to do with your parameters, looks like the issue with the dataset itself.

What you can do is try and track down corrupt images by logging them when you encounter the "Invalid PNG data" exception. Or you can just ignore them, discard the corrupted batch and keep training — might be an option, too.

There might exist some external CLI tools to check images for validity, which could help you as well, but I don't know any, unfortunately.

**Comment by alpexjava** [comment]
any idea where  can i find better place to grab tf exception to ignore and collect dodgy PNGs , please?

**Comment by emedvedev** [comment]
Try catching it right where you're running a TF session: `model.py:461` (`outputs = self.sess.run(output_feed, input_feed)`)

**Comment by alpexjava** [comment]
Ok,thx :)

**Comment by alpexjava** [comment]
Yep ! - It helped me  to skip affected batches:
~line363:
            #result = self.step(batch, self.forward_only)
            result = None
            try:
                result = self.step(batch, self.forward_only)
            except:
                skipped_counter += 1
                logging.info("[INFO AP] Step {} failed, batch skipped. Total skipped: {}".format(current_step,  skipped_counter))
                continue

Thank you. 

P.S. - Still running (~15 000 000 items, step 11 023  loss 0.000179... perplexity: 1.000765) . . . 
Алексей П., Сидней

**Comment by emedvedev** [comment]
Would you mind submitting a PR? I imagine that could be useful for others, too. 

Oh, and you could try `logging.error` instead of `logging.info` there for better log handling later :)
